name: Build Windows

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore .\LurchTracer.csproj --runtime win-x64

      - name: Build
        run: dotnet build .\LurchTracer.csproj --configuration Release --runtime win-x64 --self-contained true --no-restore

      - name: Upload build
        uses: actions/upload-artifact@v7
        with:
          name: LurchTracer-Windows-x64
          path: bin/Release/net8.0-windows/win-x64/
          if-no-files-found: error